---
- name: check if go is installed
  ansible.builtin.shell: command -v go
  register: go_exists
  ignore_errors: yes
- name: install go
  when: go_exists is failed
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go1.20.4.linux-amd64.tar.gz
    remote_src: yes
    dest: "{{ ansible_env.HOME}}/.local/"
