---
- name: check if cargo is installed
  ansible.builtin.shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
- name: Download Cargo Installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
- name: install rust/cargo
  when: cargo_exists is failed
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
- name: delete cargo installer file
  ansible.builtin.file:
    path: "/tmp/sh.rustup.rs"
    state: "absent"