---
- hosts: localhost
  roles:
    - role: comcast.sdkman
      sdkman_install_packages:
        - { candidate: maven, version: 3.8.5 }
        - { candidate: gradle, version: 7.4.2 }
        - { candidate: quarkus, version: 2.8.2.Final }
        - { candidate: java, version: 8.0.302-open }
        - { candidate: java, version: 11.0.12-open }
        - { candidate: java, version: 17.0.2-open }
      sdkman_defaults:
        gradle: '7.4.2'
        maven: 3.8.5
        java: 11.0.12-open 
